### ISSUE TITLE
可以付费找你解包吗

### ISSUE THREAD

**Issue by ulike** [mos9527/evbunpack#7]
可以付费找你解包吗

**Comment by mos9527** [comment]
抱歉，暂时不考虑这样的请求。
如果您的exe不为Enigma Virtual Box所封包，在该工具的issue下提问也无法解决您的问题。
否则，[请阅读 README 和 --help 输出](https://github.com/mos9527/evbunpack?tab=readme-ov-file#usage) 处理您的封包。
以上。感谢合作。

**Comment by ulike** [comment]
是Enigma Virtual Box封包

**Comment by mos9527** [comment]
了解；可以的话能将文件上传吗？我会在能力范围内帮您看看

**Comment by ulike** [comment]
文件太大直接上传不了，我上传到网盘了：
https://mega.nz/file/BStiXB4R#JpGDRWt2bX4TjRkXoNceIeAYrhGKxHV1tVeii_TDpks

**Comment by mos9527** [comment]
[unpacker已更新](https://github.com/mos9527/evbunpack/commit/b210180d27ea55c8d6f61a662e4cfb86484ff56a)；解包您的exe使用以下命令即可：
```bash
evbunpack mb4.dll .\extract\
evbunpack wzb.dll .\extract\
evbunpack -pe 9_70 Sungame.exe .\extract\
```
同时，附解包后的文件 https://files.catbox.moe/wte84f.zip
因缺失dll这里无法这样验证exe正确性，还请谅解

**Comment by ulike** [comment]
谢谢大佬，太感谢了！
